version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: gadzam
      POSTGRES_PASSWORD: quizdb123
      POSTGRES_DB: quizdb
    ports:
      - '5555:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
