name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker_image_build:
    name: Docker image build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract lowercase user and repository name
        id: repo-name
        run: |
          USER_LOWER=$(echo "${GITHUB_ACTOR}" | tr '[:upper:]' '[:lower:]')
          REPO_LOWER=$(echo "${GITHUB_REPOSITORY#*/}" | tr '[:upper:]' '[:lower:]')
          echo "USER_LOWER=$USER_LOWER" >> $GITHUB_ENV
          echo "REPO_LOWER=$REPO_LOWER" >> $GITHUB_ENV

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.USER_LOWER }}/${{ env.REPO_LOWER }}:${{ github.sha }}
            ghcr.io/${{ env.USER_LOWER }}/${{ env.REPO_LOWER }}:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    needs:
      - docker_image_build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull ghcr.io/gadza03/internship-quiz:main
            sudo docker stop quiz-deployment || true
            sudo docker rm quiz-deployment || true
            sudo docker run -d -p 3000:3000 --env-file .env --restart always --name quiz-deployment ghcr.io/gadza03/internship-quiz:main
